// eslint-disable-next-line import/no-anonymous-default-export
export default {
	login: "ckymn",
	id: 60356676,
	node_id: "MDQ6VXNlcjYwMzU2Njc2",
	avatar_url: "https://avatars.githubusercontent.com/u/60356676?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/ckymn",
	html_url: "https://github.com/ckymn",
	followers_url: "https://api.github.com/users/ckymn/followers",
	following_url: "https://api.github.com/users/ckymn/following{/other_user}",
	gists_url: "https://api.github.com/users/ckymn/gists{/gist_id}",
	starred_url: "https://api.github.com/users/ckymn/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/ckymn/subscriptions",
	organizations_url: "https://api.github.com/users/ckymn/orgs",
	repos_url: "https://api.github.com/users/ckymn/repos",
	events_url: "https://api.github.com/users/ckymn/events{/privacy}",
	received_events_url: "https://api.github.com/users/ckymn/received_events",
	type: "User",
	site_admin: false,
	name: "Muhammet Çokyaman",
	company: "NOXARC",
	blog: "linkedin.com/in/ckymn",
	location: "Ankara",
	email: null,
	hireable: null,
	bio: "JavaScript ☯️ ",
	twitter_username: "M_ckymn",
	public_repos: 54,
	public_gists: 0,
	followers: 30,
	following: 72,
	created_at: "2020-01-27T16:16:07Z",
	updated_at: "2021-05-11T17:53:34Z",
  };
  